CREATE DATABASE IF NOT EXISTS tarde;

USE tarde;

CREATE TABLE IF NOT EXISTS alunos ( 
    rm INT UNSIGNED NOT NULL,
    nome VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL,
    senha VARCHAR(50) NOT NULL,
    avatar VARCHAR(100) DEFAULT NULL,
    PRIMARY KEY (rm)
);
