CREATE DATABASE IF NOT EXISTS noite;
USE alunos;

CREATE TABLE IF NOT EXISTS alunos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    rm INT(5) NOT NULL,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    senha VARCHAR(255) NOT NULL,
    sexo VARCHAR(9) NOT NULL,
);